import { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
	title: 'Vercel',
	description: "Initial Template generated by @create-next-app with Vercel's layout"
}

const VercelLayout = async ({ children }: Readonly<{ children: ReactNode }>) => {
	return <main className="container">{children}</main>
}

export default VercelLayout
